import smtplib
from email.message import EmailMessage

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
      /*H1 Text alignment*/
      h1{
          color:black;
          text-align: center;
          padding: 75px;
      }

      /*GOOGLE FONT*/
      body {
          font-family: 'Work Sans', sans-serif;
          font-size: 36px;
      }

      .centre{
      display: block;
      margin-left: auto;
      margin-right: auto;
      }

      .bottom {
        bottom: 0;
      }
    </style>
    
</head>
<body style="background: rgb(127,127,213);background: linear-gradient(90deg, rgba(127,127,213,1) 0%, rgba(134,168,231,1) 50%, rgba(145,234,228,1) 100%);">
    <header>
        <div class="navbar_div">
            <ul class="navbar">
                <img class="centre" src="src_navbar_logo" alt="logo"> <!--IMAGE SRC-->
            </ul>
        </div>

        <img class="centre product_image" src="src_product_image" alt="Product Image" height:> <!--IMAGE SRC-->
        <br>
        <a class="centre" href="product_link"  style="width: 50%"><h2>product_name</h2></a> <!--PRODUCT NAME-->
        <br>
        <h2 class="centre" style="width: 50%">The price has dropped from £original_price to £current_price. That's a percentage% reduction!</h2>
        <p class="centre" style="width: 50%"> This email has been automatically generated by Price Comparison Website. You have received this email because you have consented to receive emails.</p>
        <br>
    </header>
</body>
</html>
"""

# src_navbar_logo
# src_product_image
# product_link
# product_name
# original_price
# current_price
# percentage

# Credentials & receiver emails
sender_email = "my email" 
password = 0 # Use env variables to store

# email server
server = smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login(sender_email, password)

# Message information
message = EmailMessage()
message["Subject"] = "Price Alert Website: A product you're wathing is now cheaper!"  # Insert product name?
message["From"] = sender_email
message["To"] =  # MYSQL FETCHALL
message.set_content("Please enable HTML! You will not be able to view this email without it.")
message.add_alternative(html, subtype="html")

server.send_message(message)
server.quit()
print("Sent!")

"""
- Get data from MySQL
- format it into HTML
"""
